FROM node:20

# Set working directory.
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies.
RUN npm install

# Copy the rest of the application.
COPY . .

# Make entrypoint script executable.
RUN chmod +x ./entrypoint.dev.sh

# Generate the prisma client.
RUN npm run db:generate

# Build the application.
RUN npm run build

# Copy prisma engine to dist.
RUN npm run db:prisma-engine-fix

# Expose dev port.
EXPOSE 8000

# Set entrypoint script and run the application.
ENTRYPOINT [ "./entrypoint.dev.sh" ]
CMD ["npm", "run", "dev-watch"]